# Плэйбук для создания пользователей на сервере для работы ansible.
# Создется пользователь с sudo правами и обычный пользователь, устанавливется публичный ключ ansible.
#
# Запуск:
#   ansible-playbook [-l <hostname or group>] playbooks/initial_server.yml --vault-password-file=vault.txt -kK
#   потребуется ввести пароль SSH и sudo-пароль.
# Опции:
#   [-l <hostname or group>] опционально укажите хост или группу хостов из инвентарного файла для которых будет выполняться плейбук.
#   --vault-password-file=vault.txt путь к файлу, который содержит пароль от vault хранилища с зашифрованным ключом и паролями создаваемых пользователей.
#   -u username используйте если пользватель под которым запускается плейбук отличается от удаленного пользователя сервера.
---
- hosts: all
  become: yes

  roles:
    - role: ansible_users
